Repository backendoori/ootw-backend, pull requests merged in 2024-01, with the labels that each got.

#39 🚀 게시글 작성 서비스에 이미지 저장 및 url 반환 로직 도입
  mysql/schema.sql
  src/main/java/com/backendoori/ootw/post/controller/PostController.java
  src/main/java/com/backendoori/ootw/post/domain/Post.java
  src/main/java/com/backendoori/ootw/post/dto/PostSaveRequest.java
  src/main/java/com/backendoori/ootw/post/service/PostService.java
  src/test/java/com/backendoori/ootw/avatar/controller/AvatarItemControllerTest.java
  src/test/java/com/backendoori/ootw/post/controller/PostControllerTest.java
  src/test/java/com/backendoori/ootw/post/domain/PostTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
Labels: refactoring

#40 🚀 MiniO Properties 설정 및 이미지 mocking 테스트 구현
  src/main/java/com/backendoori/ootw/config/MiniOConfig.java
  src/main/java/com/backendoori/ootw/config/MiniOProperties.java
  src/main/java/com/backendoori/ootw/post/controller/PostController.java
  src/test/java/com/backendoori/ootw/config/MiniOConfigTest.java
  src/test/java/com/backendoori/ootw/post/controller/PostControllerTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
Labels: enhancement, refactoring

#43 🚀 기상청 api로부터 현재 날씨를 불러오는 api 구현
  build.gradle
  src/main/java/com/backendoori/ootw/OotwApplication.java
  src/main/java/com/backendoori/ootw/weather/controller/WeatherController.java
  src/main/java/com/backendoori/ootw/weather/domain/BaseDateTime.java
  src/main/java/com/backendoori/ootw/weather/domain/ForecastCategory.java
  src/main/java/com/backendoori/ootw/weather/domain/ForecastResult.java
  src/main/java/com/backendoori/ootw/weather/domain/ForecastResultItem.java
  src/main/java/com/backendoori/ootw/weather/dto/WeatherResponse.java
  src/main/java/com/backendoori/ootw/weather/service/WeatherService.java
  src/main/java/com/backendoori/ootw/weather/util/BaseDateTimeCalculator.java
  src/main/java/com/backendoori/ootw/weather/util/BaseDateTimeFormatter.java
  src/main/java/com/backendoori/ootw/weather/util/ForecastProperties.java
  src/main/java/com/backendoori/ootw/weather/util/client/ForecastApi.java
  src/main/java/com/backendoori/ootw/weather/util/client/ForecastApiClient.java
  src/main/java/com/backendoori/ootw/weather/util/deserializer/ForecastResultDeserializer.java
  src/main/resources/application.yaml
  src/test/resources/application.yaml
Labels: enhancement

#49 🚀 build CI action이 작동하지 않는 버그 수정, Pull request auto assign, coverage report 설정
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/🔩-refactoring.md
  .github/workflows/ci-build-action.yml
  .github/workflows/ci-pr-build.yml
  build.gradle
  docker-compose.yml
  src/main/resources/application.yaml
  src/test/resources/application.yaml
Labels: bug, refactoring

#50 🚀 Avatarimage 업로드 시 필요한 validation 추가
  .idea/codeStyles/codeStyleConfig.xml
  src/main/java/com/backendoori/ootw/avatar/controller/AvatarItemController.java
  src/main/java/com/backendoori/ootw/avatar/domain/AvatarItem.java
  src/main/java/com/backendoori/ootw/avatar/domain/ItemType.java
  src/main/java/com/backendoori/ootw/avatar/dto/AvatarItemRequest.java
  src/main/java/com/backendoori/ootw/avatar/dto/AvatarItemResponse.java
  src/main/java/com/backendoori/ootw/common/image/MiniOImageServiceImpl.java
  src/main/java/com/backendoori/ootw/common/validation/Enum.java
  src/main/java/com/backendoori/ootw/common/validation/EnumValidator.java
  src/main/java/com/backendoori/ootw/common/validation/Image.java
  src/main/java/com/backendoori/ootw/common/validation/ImageValidator.java
  src/main/java/com/backendoori/ootw/config/MiniOConfig.java
  src/main/java/com/backendoori/ootw/exception/GlobalControllerAdvice.java
  src/main/java/com/backendoori/ootw/exception/ImageUploadException.java
  src/main/java/com/backendoori/ootw/post/controller/PostController.java
  src/main/resources/application.yaml
  src/test/java/com/backendoori/ootw/avatar/controller/AvatarItemControllerTest.java
  src/test/java/com/backendoori/ootw/avatar/domain/AvatarItemTest.java
  src/test/java/com/backendoori/ootw/common/image/MiniOImageServiceImplTest.java
Labels: enhancement

#54 🚀 사용자 인증 요청 및 user entity validation 추가
  src/main/java/com/backendoori/ootw/common/AssertUtil.java
  src/main/java/com/backendoori/ootw/exception/ExceptionResponse.java
  src/main/java/com/backendoori/ootw/exception/GlobalControllerAdvice.java
  src/main/java/com/backendoori/ootw/user/controller/UserController.java
  src/main/java/com/backendoori/ootw/user/domain/User.java
  src/main/java/com/backendoori/ootw/user/dto/LoginDto.java
  src/main/java/com/backendoori/ootw/user/dto/SignupDto.java
  src/main/java/com/backendoori/ootw/user/exception/AlreadyExistEmailException.java
  src/main/java/com/backendoori/ootw/user/exception/IncorrectPasswordException.java
  src/main/java/com/backendoori/ootw/user/service/UserService.java
  src/main/java/com/backendoori/ootw/user/validation/Message.java
  src/main/java/com/backendoori/ootw/user/validation/Password.java
  src/main/java/com/backendoori/ootw/user/validation/PasswordValidator.java
  src/main/java/com/backendoori/ootw/user/validation/RFC5322.java
  src/test/java/com/backendoori/ootw/post/controller/PostControllerTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
  src/test/java/com/backendoori/ootw/user/controller/UserControllerTest.java
  src/test/java/com/backendoori/ootw/user/domain/UserTest.java
  src/test/java/com/backendoori/ootw/user/service/UserServiceTest.java
Labels: enhancement, refactoring

#52 🚀 날씨 api 리팩토링 및 테스트 코드 작성
  .github/workflows/ci-build-action.yml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  build.gradle
  src/main/java/com/backendoori/ootw/OotwApplication.java
  src/main/java/com/backendoori/ootw/common/image/MiniOImageServiceImpl.java
  src/main/java/com/backendoori/ootw/common/validation/ImageValidator.java
  src/main/java/com/backendoori/ootw/config/OpenFeignConfig.java
  src/main/java/com/backendoori/ootw/post/domain/Post.java
  src/main/java/com/backendoori/ootw/post/dto/PostReadResponse.java
  src/main/java/com/backendoori/ootw/post/dto/PostSaveRequest.java
  src/main/java/com/backendoori/ootw/post/dto/PostSaveResponse.java
  src/main/java/com/backendoori/ootw/weather/controller/WeatherController.java
  src/main/java/com/backendoori/ootw/weather/domain/ForecastCategory.java
  src/main/java/com/backendoori/ootw/weather/domain/ForecastResult.java
  src/main/java/com/backendoori/ootw/weather/domain/ForecastResultItem.java
  src/main/java/com/backendoori/ootw/weather/domain/PtyType.java
  src/main/java/com/backendoori/ootw/weather/domain/SkyType.java
  src/main/java/com/backendoori/ootw/weather/domain/Temperature.java
  src/main/java/com/backendoori/ootw/weather/domain/Weather.java
  src/main/java/com/backendoori/ootw/weather/domain/forecast/ForecastCategory.java
  src/main/java/com/backendoori/ootw/weather/dto/WeatherDto.java
  src/main/java/com/backendoori/ootw/weather/dto/WeatherResponse.java
  src/main/java/com/backendoori/ootw/weather/dto/forecast/BaseDateTime.java
  src/main/java/com/backendoori/ootw/weather/exception/ForecastResultErrorManager.java
  src/main/java/com/backendoori/ootw/weather/service/WeatherService.java
  src/main/java/com/backendoori/ootw/weather/util/BaseDateTimeCalculator.java
  src/main/java/com/backendoori/ootw/weather/util/ForecastProperties.java
  src/main/java/com/backendoori/ootw/weather/util/client/ForecastApi.java
  src/main/java/com/backendoori/ootw/weather/util/client/ForecastApiClient.java
  src/main/java/com/backendoori/ootw/weather/util/deserializer/ForecastResultHeader.java
  src/main/java/com/backendoori/ootw/weather/util/deserializer/ForecastResultHeaderDeserializer.java
  src/main/java/com/backendoori/ootw/weather/util/deserializer/ForecastResultItem.java
  src/main/java/com/backendoori/ootw/weather/util/deserializer/ForecastResultItemSerializer.java
  src/main/java/com/backendoori/ootw/weather/util/deserializer/ForecastSuccessResultBody.java
  src/main/java/com/backendoori/ootw/weather/util/deserializer/ForecastSuccessResultBodyDeserializer.java
  src/main/resources/application.yaml
  src/test/java/com/backendoori/ootw/avatar/controller/AvatarItemControllerTest.java
  src/test/java/com/backendoori/ootw/post/controller/PostControllerTest.java
  src/test/java/com/backendoori/ootw/post/domain/PostTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
  src/test/java/com/backendoori/ootw/weather/controller/WeatherControllerTest.java
  src/test/java/com/backendoori/ootw/weather/domain/PtyTypeTest.java
  src/test/java/com/backendoori/ootw/weather/domain/SkyTypeTest.java
  src/test/java/com/backendoori/ootw/weather/domain/TemperatureTest.java
  src/test/java/com/backendoori/ootw/weather/domain/WeatherTest.java
  src/test/java/com/backendoori/ootw/weather/domain/forecast/ForecastCategoryTest.java
  src/test/java/com/backendoori/ootw/weather/exception/ForecastResultErrorManagerTest.java
  src/test/java/com/backendoori/ootw/weather/util/BaseDateTimeCalculatorTest.java
  src/test/java/com/backendoori/ootw/weather/util/client/ForecastApiClientTest.java
  src/test/resources/application.yaml
Labels: enhancement, refactoring

#55 🚀 좋아요 요청 및 취소 기능 작성
  mysql/schema.sql
  src/main/java/com/backendoori/ootw/exception/ImageUploadException.java
  src/main/java/com/backendoori/ootw/like/controller/LikeController.java
  src/main/java/com/backendoori/ootw/like/domain/Like.java
  src/main/java/com/backendoori/ootw/like/dto/controller/LikeRequest.java
  src/main/java/com/backendoori/ootw/like/dto/controller/LikeResponse.java
  src/main/java/com/backendoori/ootw/like/repository/LikeRepository.java
  src/main/java/com/backendoori/ootw/like/service/LikeService.java
  src/test/java/com/backendoori/ootw/like/controller/LikeControllerTest.java
  src/test/java/com/backendoori/ootw/like/domain/LikeTest.java
  src/test/java/com/backendoori/ootw/like/service/LikeServiceTest.java
Labels: enhancement

#57 🚀 게시글 저장할 때 날씨 api로 당일 최저/최고 기온 불러오기
  mysql/schema.sql
  src/main/java/com/backendoori/ootw/exception/ImageUploadException.java
  src/main/java/com/backendoori/ootw/post/domain/Post.java
  src/main/java/com/backendoori/ootw/post/dto/PostReadResponse.java
  src/main/java/com/backendoori/ootw/post/dto/PostSaveRequest.java
  src/main/java/com/backendoori/ootw/post/dto/PostSaveResponse.java
  src/main/java/com/backendoori/ootw/post/service/PostService.java
  src/main/java/com/backendoori/ootw/post/validation/PostValidator.java
  src/main/java/com/backendoori/ootw/user/validation/Password.java
  src/main/java/com/backendoori/ootw/weather/controller/WeatherController.java
  src/main/java/com/backendoori/ootw/weather/domain/TemperatureArrange.java
  src/main/java/com/backendoori/ootw/weather/domain/Weather.java
  src/main/java/com/backendoori/ootw/weather/dto/TemperatureArrangeDto.java
  src/main/java/com/backendoori/ootw/weather/dto/WeatherDto.java
  src/main/java/com/backendoori/ootw/weather/dto/WeatherResponse.java
  src/main/java/com/backendoori/ootw/weather/exception/ForecastResultErrorManager.java
  src/main/java/com/backendoori/ootw/weather/service/WeatherService.java
  src/main/java/com/backendoori/ootw/weather/util/BaseDateTimeCalculator.java
  src/main/java/com/backendoori/ootw/weather/util/client/ForecastApiClient.java
  src/main/java/com/backendoori/ootw/weather/util/deserializer/ForecastResultItem.java
  src/test/java/com/backendoori/ootw/post/controller/PostControllerTest.java
  src/test/java/com/backendoori/ootw/post/domain/PostTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
  src/test/java/com/backendoori/ootw/weather/domain/TemperatureArrangeTest.java
  src/test/java/com/backendoori/ootw/weather/domain/WeatherTest.java
  src/test/java/com/backendoori/ootw/weather/dto/WeatherResponseTest.java
  src/test/java/com/backendoori/ootw/weather/exception/ForecastResultErrorManagerTest.java
  src/test/java/com/backendoori/ootw/weather/util/BaseDateTimeCalculatorTest.java
  src/test/java/com/backendoori/ootw/weather/util/client/ForecastApiClientTest.java
Labels: enhancement, refactoring

#58 🚀 게시글 저장할 때 날씨 api로 당일 최저/최고 기온 불러오기
  mysql/schema.sql
  src/main/java/com/backendoori/ootw/post/domain/Post.java
  src/main/java/com/backendoori/ootw/post/dto/PostReadResponse.java
  src/main/java/com/backendoori/ootw/post/dto/PostSaveRequest.java
  src/main/java/com/backendoori/ootw/post/dto/PostSaveResponse.java
  src/main/java/com/backendoori/ootw/post/service/PostService.java
  src/main/java/com/backendoori/ootw/post/validation/PostValidator.java
  src/main/java/com/backendoori/ootw/user/validation/Password.java
  src/main/java/com/backendoori/ootw/weather/controller/WeatherController.java
  src/main/java/com/backendoori/ootw/weather/domain/TemperatureArrange.java
  src/main/java/com/backendoori/ootw/weather/domain/Weather.java
  src/main/java/com/backendoori/ootw/weather/dto/TemperatureArrangeDto.java
  src/main/java/com/backendoori/ootw/weather/dto/WeatherDto.java
  src/main/java/com/backendoori/ootw/weather/dto/WeatherResponse.java
  src/main/java/com/backendoori/ootw/weather/exception/ForecastResultErrorManager.java
  src/main/java/com/backendoori/ootw/weather/service/WeatherService.java
  src/main/java/com/backendoori/ootw/weather/util/BaseDateTimeCalculator.java
  src/main/java/com/backendoori/ootw/weather/util/client/ForecastApiClient.java
  src/main/java/com/backendoori/ootw/weather/util/deserializer/ForecastResultItem.java
  src/test/java/com/backendoori/ootw/like/controller/LikeControllerTest.java
  src/test/java/com/backendoori/ootw/like/domain/LikeTest.java
  src/test/java/com/backendoori/ootw/like/service/LikeServiceTest.java
  src/test/java/com/backendoori/ootw/post/controller/PostControllerTest.java
  src/test/java/com/backendoori/ootw/post/domain/PostTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
  src/test/java/com/backendoori/ootw/weather/domain/TemperatureArrangeTest.java
  src/test/java/com/backendoori/ootw/weather/domain/WeatherTest.java
  src/test/java/com/backendoori/ootw/weather/dto/WeatherResponseTest.java
  src/test/java/com/backendoori/ootw/weather/exception/ForecastResultErrorManagerTest.java
  src/test/java/com/backendoori/ootw/weather/util/BaseDateTimeCalculatorTest.java
  src/test/java/com/backendoori/ootw/weather/util/client/ForecastApiClientTest.java
Labels: enhancement, refactoring

#64 🚀 기존 날씨 관련 서비스 리팩토링
  http/post.http
  src/main/java/com/backendoori/ootw/post/dto/PostSaveRequest.java
  src/main/java/com/backendoori/ootw/post/service/PostService.java
  src/main/java/com/backendoori/ootw/post/validation/Message.java
  src/main/java/com/backendoori/ootw/post/validation/PostValidator.java
  src/main/java/com/backendoori/ootw/weather/controller/WeatherController.java
  src/main/java/com/backendoori/ootw/weather/domain/Coordinate.java
  src/main/java/com/backendoori/ootw/weather/domain/PtyType.java
  src/main/java/com/backendoori/ootw/weather/domain/SkyType.java
  src/main/java/com/backendoori/ootw/weather/domain/Temperature.java
  src/main/java/com/backendoori/ootw/weather/domain/TemperatureArrange.java
  src/main/java/com/backendoori/ootw/weather/domain/forecast/ForecastCategory.java
  src/main/java/com/backendoori/ootw/weather/dto/WeatherResponse.java
  src/main/java/com/backendoori/ootw/weather/exception/ForecastResultErrorManager.java
  src/main/java/com/backendoori/ootw/weather/service/WeatherService.java
  src/main/java/com/backendoori/ootw/weather/util/DateTimeProvider.java
  src/main/java/com/backendoori/ootw/weather/util/client/ForecastApiClient.java
  src/main/java/com/backendoori/ootw/weather/util/deserializer/ForecastResultItem.java
  src/main/java/com/backendoori/ootw/weather/validation/CoordinateValidator.java
  src/main/java/com/backendoori/ootw/weather/validation/Grid.java
  src/main/java/com/backendoori/ootw/weather/validation/Message.java
  src/test/java/com/backendoori/ootw/like/controller/LikeControllerTest.java
  src/test/java/com/backendoori/ootw/like/domain/LikeTest.java
  src/test/java/com/backendoori/ootw/like/service/LikeServiceTest.java
  src/test/java/com/backendoori/ootw/post/controller/PostControllerTest.java
  src/test/java/com/backendoori/ootw/post/domain/PostTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
  src/test/java/com/backendoori/ootw/util/provider/ForecastApiCommonRequestSourceProvider.java
  src/test/java/com/backendoori/ootw/util/provider/ForecastApiCommonResponseSourceProvider.java
  src/test/java/com/backendoori/ootw/util/provider/ForecastApiUltraShortResponseSourceProvider.java
  src/test/java/com/backendoori/ootw/util/provider/ForecastApiVillageResponseSourceProvider.java
  src/test/java/com/backendoori/ootw/weather/controller/WeatherControllerTest.java
  src/test/java/com/backendoori/ootw/weather/domain/PtyTypeTest.java
  src/test/java/com/backendoori/ootw/weather/domain/SkyTypeTest.java
  src/test/java/com/backendoori/ootw/weather/domain/TemperatureArrangeTest.java
  src/test/java/com/backendoori/ootw/weather/dto/WeatherResponseTest.java
  src/test/java/com/backendoori/ootw/weather/exception/ForecastResultErrorManagerTest.java
  src/test/java/com/backendoori/ootw/weather/service/WeatherServiceTest.java
  src/test/java/com/backendoori/ootw/weather/util/DateTimeProviderTest.java
  src/test/java/com/backendoori/ootw/weather/util/client/ForecastApiClientTest.java
Labels: enhancement, refactoring

#63 🚀 좋아요 기능 고도화
  mysql/schema.sql
  src/main/java/com/backendoori/ootw/avatar/domain/AvatarItem.java
  src/main/java/com/backendoori/ootw/avatar/domain/Sex.java
  src/main/java/com/backendoori/ootw/avatar/dto/AvatarItemRequest.java
  src/main/java/com/backendoori/ootw/avatar/dto/AvatarItemResponse.java
  src/main/java/com/backendoori/ootw/like/controller/LikeController.java
  src/main/java/com/backendoori/ootw/like/domain/Like.java
  src/main/java/com/backendoori/ootw/like/dto/controller/LikeResponse.java
  src/main/java/com/backendoori/ootw/like/repository/LikeRepository.java
  src/main/java/com/backendoori/ootw/like/service/LikeService.java
  src/main/java/com/backendoori/ootw/post/domain/Post.java
  src/main/java/com/backendoori/ootw/post/dto/PostReadResponse.java
  src/main/java/com/backendoori/ootw/post/repository/PostRepository.java
  src/main/java/com/backendoori/ootw/post/service/PostService.java
  src/test/java/com/backendoori/ootw/avatar/controller/AvatarItemControllerTest.java
  src/test/java/com/backendoori/ootw/avatar/domain/AvatarItemTest.java
  src/test/java/com/backendoori/ootw/avatar/service/AvatarItemServiceTest.java
  src/test/java/com/backendoori/ootw/like/controller/LikeControllerTest.java
  src/test/java/com/backendoori/ootw/like/domain/LikeTest.java
  src/test/java/com/backendoori/ootw/like/service/LikeServiceTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
Labels: enhancement

#65 🔨 2차 스프린트 리뷰 반영 - field name, validation, annotation
  build.gradle
  mysql/schema.sql
  src/main/java/com/backendoori/ootw/common/OotwMailSender.java
  src/main/java/com/backendoori/ootw/config/ExceptionHandlerConfigurer.java
  src/main/java/com/backendoori/ootw/config/HttpRequestsConfigurer.java
  src/main/java/com/backendoori/ootw/post/dto/WriterDto.java
  src/main/java/com/backendoori/ootw/security/jwt/Message.java
  src/main/java/com/backendoori/ootw/security/jwt/TokenProvider.java
  src/main/java/com/backendoori/ootw/user/controller/CertificateController.java
  src/main/java/com/backendoori/ootw/user/domain/User.java
  src/main/java/com/backendoori/ootw/user/dto/CertifyDto.java
  src/main/java/com/backendoori/ootw/user/dto/LoginDto.java
  src/main/java/com/backendoori/ootw/user/dto/SendCodeDto.java
  src/main/java/com/backendoori/ootw/user/dto/SignupDto.java
  src/main/java/com/backendoori/ootw/user/service/CertificateService.java
  src/main/java/com/backendoori/ootw/user/service/UserService.java
  src/test/java/com/backendoori/ootw/common/OotwMailSenderTest.java
  src/test/java/com/backendoori/ootw/like/controller/LikeControllerTest.java
  src/test/java/com/backendoori/ootw/like/domain/LikeTest.java
  src/test/java/com/backendoori/ootw/like/service/LikeServiceTest.java
  src/test/java/com/backendoori/ootw/post/controller/PostControllerTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
  src/test/java/com/backendoori/ootw/security/jwt/TokenProviderTest.java
  src/test/java/com/backendoori/ootw/user/controller/CertificateControllerTest.java
  src/test/java/com/backendoori/ootw/user/controller/UserControllerTest.java
  src/test/java/com/backendoori/ootw/user/domain/UserTest.java
  src/test/java/com/backendoori/ootw/user/service/CertificateServiceTest.java
  src/test/java/com/backendoori/ootw/user/service/UserServiceTest.java
Labels: refactoring

#68 🚀 API 서버 타임 존 설정
  src/main/java/com/backendoori/ootw/OotwApplication.java
  src/test/java/com/backendoori/ootw/OotwApplicationTests.java
Labels: enhancement

#66 🚀 이미지 관련 validation 추가와 각 상황에 맞는 테스트 코드 작성
  src/main/java/com/backendoori/ootw/avatar/controller/AvatarItemController.java
  src/main/java/com/backendoori/ootw/avatar/domain/AvatarItem.java
  src/main/java/com/backendoori/ootw/avatar/domain/ItemType.java
  src/main/java/com/backendoori/ootw/avatar/domain/Sex.java
  src/main/java/com/backendoori/ootw/avatar/dto/AvatarItemResponse.java
  src/main/java/com/backendoori/ootw/avatar/service/AvatarItemService.java
  src/main/java/com/backendoori/ootw/avatar/validation/AvatarImageValidator.java
  src/main/java/com/backendoori/ootw/common/image/ImageFile.java
  src/main/java/com/backendoori/ootw/common/image/ImageService.java
  src/main/java/com/backendoori/ootw/common/image/MiniOImageServiceImpl.java
  src/main/java/com/backendoori/ootw/common/image/exception/ImageControllerAdvice.java
  src/main/java/com/backendoori/ootw/common/image/exception/ImageException.java
  src/main/java/com/backendoori/ootw/common/image/exception/SaveException.java
  src/main/java/com/backendoori/ootw/common/validation/Image.java
  src/main/java/com/backendoori/ootw/common/validation/ImageAnnotationValidator.java
  src/main/java/com/backendoori/ootw/common/validation/ImageValidator.java
  src/main/java/com/backendoori/ootw/exception/GlobalControllerAdvice.java
  src/main/java/com/backendoori/ootw/exception/ImageUploadException.java
  src/main/java/com/backendoori/ootw/like/service/LikeService.java
  src/main/java/com/backendoori/ootw/post/controller/PostController.java
  src/main/java/com/backendoori/ootw/post/service/PostService.java
  src/main/java/com/backendoori/ootw/weather/controller/WeatherController.java
  src/main/resources/application.yaml
  src/test/java/com/backendoori/ootw/avatar/controller/AvatarItemControllerTest.java
  src/test/java/com/backendoori/ootw/avatar/domain/AvatarItemTest.java
  src/test/java/com/backendoori/ootw/avatar/service/AvatarItemServiceTest.java
  src/test/java/com/backendoori/ootw/common/image/MiniOImageServiceImplTest.java
  src/test/java/com/backendoori/ootw/post/controller/PostControllerTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
Labels: enhancement

#69 🚀 게시글 수정/삭제 기능 구현
  mysql/schema.sql
  src/main/java/com/backendoori/ootw/avatar/domain/AvatarItem.java
  src/main/java/com/backendoori/ootw/avatar/dto/AvatarItemResponse.java
  src/main/java/com/backendoori/ootw/config/HttpRequestsConfigurer.java
  src/main/java/com/backendoori/ootw/exception/GlobalControllerAdvice.java
  src/main/java/com/backendoori/ootw/exception/PermissionException.java
  src/main/java/com/backendoori/ootw/post/controller/PostController.java
  src/main/java/com/backendoori/ootw/post/domain/Post.java
  src/main/java/com/backendoori/ootw/post/dto/request/PostSaveRequest.java
  src/main/java/com/backendoori/ootw/post/dto/request/PostUpdateRequest.java
  src/main/java/com/backendoori/ootw/post/dto/response/PostReadResponse.java
  src/main/java/com/backendoori/ootw/post/dto/response/PostSaveUpdateResponse.java
  src/main/java/com/backendoori/ootw/post/dto/response/WriterDto.java
  src/main/java/com/backendoori/ootw/post/service/PostService.java
  src/main/java/com/backendoori/ootw/post/validation/Message.java
  src/main/java/com/backendoori/ootw/post/validation/PostValidator.java
  src/main/java/com/backendoori/ootw/user/domain/User.java
  src/main/resources/application.yaml
  src/test/java/com/backendoori/ootw/like/controller/LikeControllerTest.java
  src/test/java/com/backendoori/ootw/like/domain/LikeTest.java
  src/test/java/com/backendoori/ootw/like/service/LikeServiceTest.java
  src/test/java/com/backendoori/ootw/post/controller/PostControllerTest.java
  src/test/java/com/backendoori/ootw/post/domain/PostTest.java
  src/test/java/com/backendoori/ootw/post/service/PostServiceTest.java
  src/test/java/com/backendoori/ootw/weather/domain/TemperatureArrangeTest.java
Labels: enhancement, refactoring

#77 🔨 좋아요가 있는 게시글 삭제 가능하도록 ON DELETE CASCADE 설정
  mysql/schema.sql
Labels: bug

#75 🚀 Restdocs를 활용한 #OOTW API 명세서 작성
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/index.html
  src/main/java/com/backendoori/ootw/like/controller/LikeController.java
  src/test/java/com/backendoori/ootw/document/avatar/AvatarItemDocumentationTest.java
  src/test/java/com/backendoori/ootw/document/common/ApiDocumentUtil.java
  src/test/java/com/backendoori/ootw/document/like/LikeDocumentationTest.java
  src/test/java/com/backendoori/ootw/document/post/PostDocumentationTest.java
  src/test/java/com/backendoori/ootw/document/user/CertificateDocumentationTest.java
  src/test/java/com/backendoori/ootw/document/user/UserDocumentationTest.java
  src/test/java/com/backendoori/ootw/document/weather/WeatherDocumentationTest.java
  src/test/java/com/backendoori/ootw/user/controller/CertificateControllerTest.java
  src/test/java/com/backendoori/ootw/user/controller/UserControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-headers.snippet
Labels: enhancement

#79 🚀 Redis TTL 설정을 통한 이메일 인증 만료 기능 추가
  src/main/java/com/backendoori/ootw/user/domain/Certificate.java
  src/main/java/com/backendoori/ootw/user/exception/ExpiredCertificateException.java
  src/main/java/com/backendoori/ootw/user/service/CertificateService.java
  src/test/java/com/backendoori/ootw/user/service/CertificateServiceTest.java
Labels: enhancement

#83 리드미 작성
  README.md
Labels: documentation

#84 docs: 메인 이미지 추가
  README.md
Labels: documentation
